// Generates every published copy of the skill from skills/<name>/SKILL.md.
// Run with --check to fail instead of writing (used by the test suite).
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const SKILL = "showmeatsack";
const CONSTANT = "SHOWMEATSACK_SKILL_MARKDOWN";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = join(root, "skills", SKILL, "SKILL.md");
const check = process.argv.includes("--check");

const readText = (path) => readFileSync(path, "utf8").replace(/\r\n/g, "\n");

const raw = readText(source);
const match = raw.match(/^---\n([\s\S]*?)\n---\n+([\s\S]*)$/);
if (!match) {
  throw new Error(`${source} is missing YAML frontmatter`);
}
const body = match[2];

const escaped = body.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const outputs = [
  {
    path: join(root, "src", "lib", `${SKILL}-skill.ts`),
    contents:
      `// Generated by scripts/sync-skill.mjs from skills/${SKILL}/SKILL.md. Do not edit.\n` +
      `export const ${CONSTANT} = \`${escaped}\`;\n`,
  },
  // Cursor reads this copy from disk. It keeps the frontmatter so the
  // description drives triggering there too.
  { path: join(root, ".cursor", "skills", SKILL, "SKILL.md"), contents: raw },
];

let stale = false;
for (const { path, contents } of outputs) {
  let current = null;
  try {
    current = readText(path);
  } catch {}
  if (current === contents) continue;
  if (check) {
    stale = true;
    console.error(`stale: ${path.slice(root.length + 1)}`);
    continue;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents);
  console.log(`wrote ${path.slice(root.length + 1)}`);
}

if (stale) {
  console.error(`\nRun \`pnpm sync:skill\` after editing skills/${SKILL}/SKILL.md.`);
  process.exit(1);
}
